language: php

php:
  - 5.6
  - 7.0
  
before_script:
  - mysql -u root -e 'CREATE DATABASE list3;'
  - mysql -u root list3 < sql/db.sql
  
script:
  - phpunit                  #default test command
  - phpunit -c phpunit.xml   #custom test command to make sure CLI args don't break the test