language: php

php:
  - 5.6
  - 7.0
  
before_script:
  - mysql -u root -e 'CREATE DATABASE gabs;'
  - mysql -u root gabs < sql/db.sql
  - mysql -u root -p root root
  
script:
  - phpunit                  #default test command
  - phpunit -c phpunit.xml   #custom test command to make sure CLI args don't break the test