language: php

php:
  - 5.6
  - 7.0
  
install:
  - curl -s http://getcomposer.org/installer | php
  - composer install --prefer-dist --dev --no-interaction
script:
  - mkdir -p report/html
  - phpunit                  #default test command
  - phpunit -c phpunit.xml   #custom test command to make sure CLI args don't break the test
  
after_script:  
  - travis_retry php vendor/bin/coveralls -v
  