language: php

php:
  - 5.6
  - 7.0
  
install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction


before_script:
  - sudo mysql -e 'CREATE DATABASE gabs;use gabs;set names utf8;source sql/db.sql;'
  - sudo mysql -e "use mysql;update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';grant all privileges on *.* to 'root'@'localhost' identified by 'root' with grant option;FLUSH PRIVILEGES;"
  
script:
  - mkdir -p report/html
  - phpunit                  #default test command
  - phpunit -c phpunit.xml   #custom test command to make sure CLI args don't break the test
  
after_script:
  - travis_retry php vendor/bin/php-coveralls -v