# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.0-apache-stretch-node-browsers
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_HOST: 127.0.0.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

          
    steps:
      - checkout
      - run:
          name: Install things we need
          command: |
            sudo apt-get -y update
            sudo apt-get install php7.0-mysql
            sudo dpkg-reconfigure php7.0-mysql
            
            sudo apt-get install mysql-client
            sudo apt-get -y install mysql-server
            
      - run:
          name: Start database server
          command: |
            sudo service mysql start
            sleep 2
            ps aux | grep mysql
            
      - run:
          name: Set DB
          command: |
            sudo mysql -e 'CREATE DATABASE gabs;use gabs;set names utf8;source sql/db.sql;'
            
      - run:
          name: Init phpunit
          command: |
            sudo wget https://phar.phpunit.de/phpunit.phar
            sudo chmod +x phpunit.phar
            sudo mv phpunit.phar /usr/local/bin/phpunit
            
      - run:
          name: Run tests
          command: |
            phpunit